topics: "./data/config/topics.yaml"
facebook: "./data/messages/facebook"
instagram: "./data/messages/instagram"
whatsapp: "./data/messages/whatsapp"
senders: "./data/config/senders.yaml"
cache_chat: "./data/cache/chat"
cache_df_words: "./data/cache/words"
cache_df_topics: "./data/cache/topics"
stopwords: "./data/config/stopwords.txt"
